name: aad_oauth
description: A Flutter OAuth package for performing user authentication against Azure Active Directory OAuth2 v2.0 endpoint.
version: 0.1.2
author: Earlybyte Gmbh <info@earlybyte.ch>
homepage: https://github.com/Earlybyte/aad_oauth

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_webview_plugin: ^0.3.0+2
  http: ^0.12.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter